name: Scrape

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      STATE_FILE: state.json
      RESULT_FILE: README.md
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run DID exporter
        run: bun run ./scripts/export-dids.ts

      - name: Run Markdown generator
        run: bun run ./scripts/generate-markdown.ts

      - name: Push to repository
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

          git add README.md state.json
          git commit -m "update: $(date --iso-8601=seconds)" || exit 0
          git push
